# Generated by Django 4.0 on 2022-01-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='approved',
        ),
    ]
